const C = {
  'ADD_TODO': 'ADD_TODO',
  'FETCH_TODOS': 'FETCH_TODOS',
  'FETCH_TODO': 'FETCH_TODO',
  'DELETE_TODO':'DELETE_TODO',
  'REMOVE_TODOS': 'REMOVE_TODOS',
  'COMPLETE_TODO': 'COMPLETE_TODO',
  'AUTHENTICATED': 'AUTHENTICATED',
  'UNAUTHENTICATED': 'UNAUTHENTICATED',
  'AUTHENTICATION_ERROR': 'AUTHENTICATION_ERROR',
  'ADD_USER_DATA': 'ADD_USER_DATA',
  'REMOVE_USER_DATA':'REMOVE_USER_DATA',
  'ADD_COUNTER': 'ADD_COUNTER'
}

export default C
