const C = {
  'ADD_TODO': 'ADD_TODO',
  'FETCH_TODO': 'FETCH_TODO',
  'DELETE_TODO':'DELETE_TODO',
  'REMOVE_TODOS': 'REMOVE_TODOS',
  'AUTHENTICATED': 'AUTHENTICATED',
  'UNAUTHENTICATED': 'UNAUTHENTICATED',
  'AUTHENTICATION_ERROR': 'AUTHENTICATION_ERROR',
  'ADD_USER_DATA': 'ADD_USER_DATA',
  'REMOVE_USER_DATA':'REMOVE_USER_DATA'
}

export default C
