const C = {
  'ADD_TODO': 'ADD_TODO',
  'FETCH_TODO': 'FETCH_TODO',
  'AUTHENTICATED': 'AUTHENTICATED',
  'UNAUTHENTICATED': 'UNAUTHENTICATED',
  'AUTHENTICATION_ERROR': 'AUTHENTICATION_ERROR',
  'USER_DATA': 'USER_DATA',
  'DELETE_TODO':'DELETE_TODO'
}

export default C
